In [1]:
import pandas as pd

In [21]:
res_df = pd.read_csv("synth_results_4.csv")
res_df = res_df[res_df['dist_weight'] == '[0.9, 0.1, 0]'].drop('dist_weight', axis=1)
res_df.rename(columns={'seed': 'method', 'method': 'seed'}, inplace=True)

In [4]:
# res_df1.sort_values(['dataset', 'bcv', 'dropout']).to_csv('syth_results_many_sorted.csv')

In [5]:
# res_df_merge1['recon_weights'] = res_df_merge1['recon_weights'].apply(lambda x: (x == '[0.9, 0.1, 0]'))
# res_df_merge1.rename(columns={'recon_weights': 'Reconstruction Loss'}, inplace=True)

In [6]:
# res_df_merge2['recon_weights'] = res_df_merge2['recon_weights'].apply(lambda x: (x == '[0.9, 0.1, 0]'))
# res_df_merge2.rename(columns={'recon_weights': 'Reconstruction Loss'}, inplace=True)

In [7]:
# res_df_merge1.sort_values(['seedmethod', 'bcv', 'Reconstruction Loss'], inplace=True)

In [8]:
# res_df_merge2.sort_values(['seedmethod', 'bcv', 'Reconstruction Loss'], inplace=True)

In [9]:
# cols = ['seedmethod', 'bcv', 'dropout', 'Reconstruction Loss', 'demap', 'accuracy', 'recon score']
# res_df_merge1 = res_df_merge1[cols]
# res_df_merge2 = res_df_merge2[cols]

In [10]:
import pandas as pd

mean_df = res_df.groupby(['method', 'bcv', 'dropout']).mean().round(3)
std_df = res_df.groupby(['method', 'bcv', 'dropout']).std().round(3)

# Merge the mean and std dataframes
combined_df = mean_df.merge(std_df, left_index=True, right_index=True, suffixes=('_mean', '_std'))

# Format the results into a single column for each feature
for col in mean_df.columns:  # Iterate directly through the columns
    combined_df[col] = combined_df[col+'_mean'].astype(str) + "(±" + combined_df[col+'_std'].astype(str) + ")"
    # Since we're directly modifying the combined_df, no need to drop the columns in this loop

# Drop the original mean and std columns after processing
combined_df1 = combined_df.loc[:, ~combined_df.columns.str.contains('_mean|_std')]
combined_df1.drop(['seed', 'accuracy'], axis=1, inplace=True)

/tmp/ipykernel_2844388/1769759544.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df1.drop(['seed', 'accuracy'], axis=1, inplace=True)

In [11]:
combined_df1.to_csv('synth_res_4_final.csv', index=False)

In [12]:
combined_df1

                             demap    recon score    demap_phate
method bcv  dropout
groups 0.00 0.5      0.704(±0.087)   0.849(±0.02)  0.721(±0.086)
       0.18 0.5       0.72(±0.092)  0.783(±0.017)  0.746(±0.066)
       0.25 0.5      0.716(±0.069)  0.724(±0.034)  0.717(±0.075)
       0.50 0.5      0.439(±0.208)  0.416(±0.041)  0.397(±0.185)
paths  0.00 0.5      0.669(±0.129)   0.759(±0.01)  0.682(±0.117)
       0.18 0.5       0.664(±0.11)  0.673(±0.065)   0.66(±0.111)
       0.25 0.5       0.65(±0.116)  0.588(±0.086)  0.632(±0.128)
       0.50 0.5      0.339(±0.174)   0.35(±0.053)  0.311(±0.155)

In [22]:
res_df_aff = pd.read_csv("affinity_synth_results_4.csv")
res_df_aff.rename(columns={'seed': 'method', 'method': 'seed'}, inplace=True)
res_df_aff.drop(['probmethod', 'alpha', 'knn'], axis=1, inplace=True)

In [23]:
res_df_aff

    method  seed   bcv  dropout     demap  accuracy  recon score
0   groups     2  0.00      0.5  0.558445  0.071780     0.855537
1    paths     3  0.25      0.5  0.771160  0.059344     0.561576
2    paths     3  0.00      0.5  0.795115  0.097351     0.712966
3   groups     2  0.25      0.5  0.662904  0.368685     0.730877
4   groups     1  0.00      0.5  0.574291  0.103225     0.841746
5   groups     1  0.50      0.5  0.089648  0.147770     0.282181
6   groups     3  0.25      0.5  0.807537  0.051950     0.644407
7    paths     1  0.18      0.5  0.684583  0.206991     0.692633
8    paths     1  0.25      0.5  0.664871  0.084145     0.588807
9    paths     2  0.25      0.5  0.651481  0.085769     0.579634
10  groups     3  0.50      0.5  0.381554  0.109267     0.364036
11  groups     2  0.50      0.5  0.332107  0.180460     0.273171
12   paths     1  0.50      0.5  0.188351  0.241928     0.298378
13   paths     1  0.00      0.5  0.637777  0.097705     0.766795
14   paths     3  0.50      0.5  0.350770  0.116049     0.330617
15  groups     4  0.00      0.5  0.576839  0.104930     0.549388
16   paths     2  0.18      0.5  0.650361  0.104768     0.619944
17  groups     1  0.25      0.5  0.636524  0.125833     0.658311
18   paths     2  0.00      0.5  0.608382  0.073533     0.735862
19   paths     3  0.18      0.5  0.802367  0.090727     0.641543
20  groups     4  0.50      0.5  0.275838  0.121551     0.305299
21  groups     4  0.25      0.5  0.776391  0.057228     0.667633
22  groups     1  0.18      0.5  0.591536  0.212398     0.758404
23  groups     3  0.00      0.5  0.785259  0.079950     0.794568
24  groups     3  0.18      0.5  0.822713  0.112843     0.714816
25   paths     2  0.50      0.5  0.262474  0.296221     0.217768
26   paths     4  0.18      0.5  0.632322  0.077453     0.480519
27  groups     2  0.18      0.5  0.636738  0.055450     0.800998
28  groups     4  0.18      0.5  0.716908  0.056391     0.730168

In [24]:
import pandas as pd

mean_df = res_df_aff.groupby(['method', 'bcv', 'dropout']).mean().round(3)
std_df = res_df_aff.groupby(['method', 'bcv', 'dropout']).std().round(3)

# Merge the mean and std dataframes
combined_df = mean_df.merge(std_df, left_index=True, right_index=True, suffixes=('_mean', '_std'))

# Format the results into a single column for each feature
for col in mean_df.columns:  # Iterate directly through the columns
    combined_df[col] = combined_df[col+'_mean'].astype(str) + "(±" + combined_df[col+'_std'].astype(str) + ")"
    # Since we're directly modifying the combined_df, no need to drop the columns in this loop

# Drop the original mean and std columns after processing
combined_df1_aff = combined_df.loc[:, ~combined_df.columns.str.contains('_mean|_std')]
combined_df1_aff.drop(['seed', 'accuracy'], axis=1, inplace=True)

/tmp/ipykernel_2844388/2539136726.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df1_aff.drop(['seed', 'accuracy'], axis=1, inplace=True)

In [25]:
combined_df1_aff

                             demap    recon score
method bcv  dropout
groups 0.00 0.5      0.624(±0.108)   0.76(±0.143)
       0.18 0.5      0.692(±0.101)  0.751(±0.038)
       0.25 0.5      0.721(±0.084)  0.675(±0.038)
       0.50 0.5       0.27(±0.128)  0.306(±0.041)
paths  0.00 0.5         0.68(±0.1)  0.739(±0.027)
       0.18 0.5      0.692(±0.076)  0.609(±0.091)
       0.25 0.5      0.696(±0.066)  0.577(±0.014)
       0.50 0.5      0.267(±0.081)  0.282(±0.058)

In [27]:
combined_df1

                             demap    recon score    demap_phate
method bcv  dropout
groups 0.00 0.5      0.704(±0.087)   0.849(±0.02)  0.721(±0.086)
       0.18 0.5       0.72(±0.092)  0.783(±0.017)  0.746(±0.066)
       0.25 0.5      0.716(±0.069)  0.724(±0.034)  0.717(±0.075)
       0.50 0.5      0.439(±0.208)  0.416(±0.041)  0.397(±0.185)
paths  0.00 0.5      0.669(±0.129)   0.759(±0.01)  0.682(±0.117)
       0.18 0.5       0.664(±0.11)  0.673(±0.065)   0.66(±0.111)
       0.25 0.5       0.65(±0.116)  0.588(±0.086)  0.632(±0.128)
       0.50 0.5      0.339(±0.174)   0.35(±0.053)  0.311(±0.155)

In [30]:
demap_dist = combined_df1[['demap', 'demap_phate']]
recon_dist = combined_df1[['recon score']]
demap_aff = combined_df1_aff[['demap']]
recon_aff = combined_df1_aff[['recon score']]

In [32]:
demap_dist.rename(columns={'demap': 'Dist.', 'demap_phate': 'PHATE'}, inplace=True)
recon_dist.rename(columns={'recon score': 'Dist.'}, inplace=True)
demap_aff.rename(columns={'demap': 'Affi.'}, inplace=True)
recon_aff.rename(columns={'recon score': 'Affi.'}, inplace=True)

/tmp/ipykernel_2844388/2737899579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demap_dist.rename(columns={'demap': 'Dist.', 'demap_phate': 'PHATE'}, inplace=True)
/tmp/ipykernel_2844388/2737899579.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recon_dist.rename(columns={'recon score': 'Dist.'}, inplace=True)
/tmp/ipykernel_2844388/2737899579.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demap_aff.rename(columns={'demap': 'Affi.'}, inplace=True)
/tmp/ipykernel_2844388/2737899579.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recon_aff.rename(columns={'recon score': 'Affi.'}, inplace=True)

In [37]:
pd.DataFrame.join(demap_aff, demap_dist)

                             Affi.          Dist.          PHATE
method bcv  dropout
groups 0.00 0.5      0.624(±0.108)  0.704(±0.087)  0.721(±0.086)
       0.18 0.5      0.692(±0.101)   0.72(±0.092)  0.746(±0.066)
       0.25 0.5      0.721(±0.084)  0.716(±0.069)  0.717(±0.075)
       0.50 0.5       0.27(±0.128)  0.439(±0.208)  0.397(±0.185)
paths  0.00 0.5         0.68(±0.1)  0.669(±0.129)  0.682(±0.117)
       0.18 0.5      0.692(±0.076)   0.664(±0.11)   0.66(±0.111)
       0.25 0.5      0.696(±0.066)   0.65(±0.116)  0.632(±0.128)
       0.50 0.5      0.267(±0.081)  0.339(±0.174)  0.311(±0.155)

In [38]:
pd.DataFrame.join(recon_aff, recon_dist)

                             Affi.          Dist.
method bcv  dropout
groups 0.00 0.5       0.76(±0.143)   0.849(±0.02)
       0.18 0.5      0.751(±0.038)  0.783(±0.017)
       0.25 0.5      0.675(±0.038)  0.724(±0.034)
       0.50 0.5      0.306(±0.041)  0.416(±0.041)
paths  0.00 0.5      0.739(±0.027)   0.759(±0.01)
       0.18 0.5      0.609(±0.091)  0.673(±0.065)
       0.25 0.5      0.577(±0.014)  0.588(±0.086)
       0.50 0.5      0.282(±0.058)   0.35(±0.053)