In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
data_names0 = ['hemisphere_none_0','ellipsoid_none_0','torus_none_0','saddle_none_0'] + ['ellipsoid_15_0', 'ellipsoid_15_0.1', 'ellipsoid_15_0.3', 'ellipsoid_15_0.5', 'ellipsoid_15_0.7', 'ellipsoid_none_0.1', 'ellipsoid_5_0.1', 'ellipsoid_10_0.1', 'ellipsoid_15_0.1', 'ellipsoid_50_0.1', 'hemisphere_15_0', 'hemisphere_15_0.1', 'hemisphere_15_0.3', 'hemisphere_15_0.5', 'hemisphere_15_0.7', 'hemisphere_none_0.1', 'hemisphere_5_0.1', 'hemisphere_10_0.1', 'hemisphere_15_0.1', 'hemisphere_50_0.1', 'saddle_15_0', 'saddle_15_0.1', 'saddle_15_0.3', 'saddle_15_0.5', 'saddle_15_0.7', 'saddle_none_0.1', 'saddle_5_0.1', 'saddle_10_0.1', 'saddle_15_0.1', 'saddle_50_0.1', 'torus_15_0', 'torus_15_0.1', 'torus_15_0.3', 'torus_15_0.5', 'torus_15_0.7', 'torus_none_0.1', 'torus_5_0.1', 'torus_10_0.1', 'torus_15_0.1', 'torus_50_0.1'] + ['saddle_10_0.1', 'saddle_50_0.1']
# data_names = [f'{n}.0' if n.endswith('_0') else n for n in data_names0 ]
data_names = data_names0

In [3]:
res_list = []
missing_list = []
for name in data_names:
    try:
        res_df = pd.read_csv(f'results/{name}/{name}.csv')
        res_list.append(res_df)
    except:
        missing_list.append(name)
        continue
results = pd.concat(res_list)

In [4]:
results

            data_name      method      corr        mse  dist2geod
0   hemisphere_none_0        ours  0.983717   0.030749   0.006986
1   hemisphere_none_0  no density  0.910126   0.328954   0.074433
2   hemisphere_none_0     density  0.914932   0.287929   0.028052
0    ellipsoid_none_0        ours  0.960778   0.492454   0.035831
1    ellipsoid_none_0  no density  0.847388   2.403414   0.106092
..                ...         ...       ...        ...        ...
1       saddle_10_0.1  no density  0.892964  92.716920   1.076311
2       saddle_10_0.1     density  0.938844   0.622122   0.023165
0       saddle_50_0.1        ours  0.877580  61.194237   0.199047
1       saddle_50_0.1  no density       NaN        NaN        NaN
2       saddle_50_0.1     density       NaN        NaN        NaN

[138 rows x 5 columns]

In [5]:
missing_list

[]

In [6]:
for name in results['data_name'].unique():
    print(results[results['data_name']==name])
    print('')

           data_name      method      corr       mse  dist2geod
0  hemisphere_none_0        ours  0.983717  0.030749   0.006986
1  hemisphere_none_0  no density  0.910126  0.328954   0.074433
2  hemisphere_none_0     density  0.914932  0.287929   0.028052

          data_name      method      corr       mse  dist2geod
0  ellipsoid_none_0        ours  0.960778  0.492454   0.035831
1  ellipsoid_none_0  no density  0.847388  2.403414   0.106092
2  ellipsoid_none_0     density  0.922390  2.243079   0.032896

      data_name      method      corr       mse  dist2geod
0  torus_none_0        ours  0.982601  0.353004   0.065092
1  torus_none_0  no density  0.907541  1.829810   0.085663
2  torus_none_0     density  0.968065  1.796790   0.015130

       data_name      method      corr       mse  dist2geod
0  saddle_none_0        ours  0.955881  0.054671   0.013050
1  saddle_none_0  no density  0.949982  0.065696   0.033616
2  saddle_none_0     density  0.964598  0.095990   0.006502

        data_name      method      corr        mse  dist2geod
0  ellipsoid_15_0        ours  0.964368   2.035977   0.019174
1  ellipsoid_15_0  no density  0.647870  36.645120   0.355047
2  ellipsoid_15_0     density  0.975827   1.499815   0.007573

          data_name      method      corr         mse  dist2geod
0  ellipsoid_15_0.1        ours  0.844497    1.105053   0.041234
1  ellipsoid_15_0.1  no density  0.339181  216.686680   0.964497
2  ellipsoid_15_0.1     density  0.849416    1.087640   0.021120
0  ellipsoid_15_0.1        ours  0.844497    1.105053   0.041234
1  ellipsoid_15_0.1  no density  0.339181  216.686680   0.964497
2  ellipsoid_15_0.1     density  0.849416    1.087640   0.021120

          data_name      method      corr         mse  dist2geod
0  ellipsoid_15_0.3        ours  0.753638   22.118662   0.209805
1  ellipsoid_15_0.3  no density  0.198393  445.388120   1.285310
2  ellipsoid_15_0.3     density  0.650709   25.624980   0.093952

          data_name      method      corr        mse  dist2geod
0  ellipsoid_15_0.5        ours  0.055485   67.72911   0.536565
1  ellipsoid_15_0.5  no density  0.155580  511.49360   1.357551
2  ellipsoid_15_0.5     density  0.323683   65.60527   0.259992

          data_name      method      corr         mse  dist2geod
0  ellipsoid_15_0.7        ours -0.097121   141.54318   1.280637
1  ellipsoid_15_0.7  no density  0.374572  1354.04810   3.723635
2  ellipsoid_15_0.7     density  0.056453   214.86984   0.673461

            data_name      method      corr       mse  dist2geod
0  ellipsoid_none_0.1        ours  0.883264  0.960033   0.128898
1  ellipsoid_none_0.1  no density  0.774349  2.774656   0.101949
2  ellipsoid_none_0.1     density  0.846819  3.033927   0.046867

         data_name      method      corr        mse  dist2geod
0  ellipsoid_5_0.1        ours  0.972209   0.351397   0.018771
1  ellipsoid_5_0.1  no density  0.763856  18.870108   0.424878
2  ellipsoid_5_0.1     density  0.948084   0.839684   0.018101

          data_name      method      corr         mse  dist2geod
0  ellipsoid_10_0.1        ours  0.929035    1.911836   0.051497
1  ellipsoid_10_0.1  no density  0.546894  145.712940   0.954739
2  ellipsoid_10_0.1     density  0.931946    1.705096   0.025650

          data_name      method      corr          mse  dist2geod
0  ellipsoid_50_0.1        ours  0.715992    46.730690   0.098836
1  ellipsoid_50_0.1  no density  0.601517  1615.541100   1.174061
2  ellipsoid_50_0.1     density  0.864251    52.442253   0.038351

         data_name      method      corr       mse  dist2geod
0  hemisphere_15_0        ours  0.987218  0.103161   0.012050
1  hemisphere_15_0  no density  0.793252  6.798230   0.162265
2  hemisphere_15_0     density  0.961460  0.113902   0.012868

           data_name      method      corr         mse  dist2geod
0  hemisphere_15_0.1        ours  0.919996    1.244105   0.068379
1  hemisphere_15_0.1  no density  0.529895  152.822360   1.011117
2  hemisphere_15_0.1     density  0.875065    1.687486   0.048325
0  hemisphere_15_0.1        ours  0.919996    1.244105   0.068379
1  hemisphere_15_0.1  no density  0.529895  152.822360   1.011117
2  hemisphere_15_0.1     density  0.875065    1.687486   0.048325

           data_name      method  corr  mse  dist2geod
0  hemisphere_15_0.3        ours   NaN  NaN        NaN
1  hemisphere_15_0.3  no density   NaN  NaN        NaN
2  hemisphere_15_0.3     density   NaN  NaN        NaN

           data_name      method      corr        mse  dist2geod
0  hemisphere_15_0.5        ours  0.122618  74.192900   1.185667
1  hemisphere_15_0.5  no density  0.129609  43.418420   0.932294
2  hemisphere_15_0.5     density  0.128569  41.589947   0.893325

           data_name      method      corr        mse  dist2geod
0  hemisphere_15_0.7        ours -0.011333  163.22604   2.660877
1  hemisphere_15_0.7  no density -0.130750  448.56950   3.761215
2  hemisphere_15_0.7     density  0.096030  203.15561   1.186689

             data_name      method      corr       mse  dist2geod
0  hemisphere_none_0.1        ours  0.896748  0.203478   0.019162
1  hemisphere_none_0.1  no density  0.538173  1.116456   0.199500
2  hemisphere_none_0.1     density  0.841862  0.262135   0.082327

          data_name      method      corr       mse  dist2geod
0  hemisphere_5_0.1        ours  0.912996  0.154587   0.023776
1  hemisphere_5_0.1  no density  0.119665  9.044512   0.387549
2  hemisphere_5_0.1     density  0.893816  0.141027   0.049520

           data_name      method      corr        mse  dist2geod
0  hemisphere_10_0.1        ours  0.823044   1.023002        inf
1  hemisphere_10_0.1  no density  0.041318  97.409004        inf
2  hemisphere_10_0.1     density  0.773739   1.137698        inf

           data_name      method      corr          mse  dist2geod
0  hemisphere_50_0.1        ours  0.843492    53.458824   0.214970
1  hemisphere_50_0.1  no density  0.316282  1696.720500   2.403678
2  hemisphere_50_0.1     density  0.869244    57.943855   0.098794

     data_name      method      corr       mse  dist2geod
0  saddle_15_0        ours  0.966252  0.572932   0.009424
1  saddle_15_0  no density  0.905548  8.430345   0.145495
2  saddle_15_0     density  0.967537  0.208880   0.005938

       data_name      method      corr        mse  dist2geod
0  saddle_15_0.1        ours  0.879231   2.389909   0.083824
1  saddle_15_0.1  no density  0.909726  11.082075   0.164622
2  saddle_15_0.1     density       NaN        NaN        NaN
0  saddle_15_0.1        ours  0.879231   2.389909   0.083824
1  saddle_15_0.1  no density  0.909726  11.082075   0.164622
2  saddle_15_0.1     density       NaN        NaN        NaN

       data_name      method      corr         mse  dist2geod
0  saddle_15_0.3        ours  0.580969   23.174990   0.491341
1  saddle_15_0.3  no density  0.735153  353.123470   1.953057
2  saddle_15_0.3     density  0.538737   32.210617   0.246964

       data_name      method      corr        mse  dist2geod
0  saddle_15_0.5        ours  0.604170   86.20610   1.223219
1  saddle_15_0.5  no density  0.401537  467.23250   2.678329
2  saddle_15_0.5     density  0.126772   97.27101   0.624797

       data_name      method      corr        mse  dist2geod
0  saddle_15_0.7        ours  0.262683  142.46303   2.275657
1  saddle_15_0.7  no density  0.432023  342.57404   2.900683
2  saddle_15_0.7     density  0.362117  198.42429   1.030705

         data_name      method      corr       mse  dist2geod
0  saddle_none_0.1        ours  0.891685  0.221124   0.039326
1  saddle_none_0.1  no density  0.793581  0.573723   0.114373
2  saddle_none_0.1     density  0.909642  0.189681   0.023706

      data_name      method      corr        mse  dist2geod
0  saddle_5_0.1        ours  0.944305   0.261075   0.034695
1  saddle_5_0.1  no density  0.854009  18.103580   0.670329
2  saddle_5_0.1     density  0.925389   0.224432   0.028029

       data_name      method      corr        mse  dist2geod
0  saddle_10_0.1        ours  0.866369   0.743272   0.048839
1  saddle_10_0.1  no density  0.892964  92.716920   1.076311
2  saddle_10_0.1     density  0.938844   0.622122   0.023165
0  saddle_10_0.1        ours  0.866369   0.743272   0.048839
1  saddle_10_0.1  no density  0.892964  92.716920   1.076311
2  saddle_10_0.1     density  0.938844   0.622122   0.023165

       data_name      method     corr        mse  dist2geod
0  saddle_50_0.1        ours  0.87758  61.194237   0.199047
1  saddle_50_0.1  no density      NaN        NaN        NaN
2  saddle_50_0.1     density      NaN        NaN        NaN
0  saddle_50_0.1        ours  0.87758  61.194237   0.199047
1  saddle_50_0.1  no density      NaN        NaN        NaN
2  saddle_50_0.1     density      NaN        NaN        NaN

    data_name      method      corr        mse  dist2geod
0  torus_15_0        ours  0.985534   4.657887   0.018877
1  torus_15_0  no density  0.745251  26.994568   0.262436
2  torus_15_0     density  0.988648   1.754116   0.016957

      data_name      method      corr         mse  dist2geod
0  torus_15_0.1        ours  0.947530    1.851111   0.040785
1  torus_15_0.1  no density  0.795799  748.270300   1.596737
2  torus_15_0.1     density  0.935089    1.431056   0.019890
0  torus_15_0.1        ours  0.947530    1.851111   0.040785
1  torus_15_0.1  no density  0.795799  748.270300   1.596737
2  torus_15_0.1     density  0.935089    1.431056   0.019890

      data_name      method      corr         mse  dist2geod
0  torus_15_0.3        ours  0.722177   23.825966   0.328753
1  torus_15_0.3  no density  0.296211  724.035900   2.953442
2  torus_15_0.3     density  0.777118   23.668537   0.134033

      data_name      method     corr       mse  dist2geod
0  torus_15_0.5        ours  0.70511  30.97057   0.493515
1  torus_15_0.5  no density      NaN       NaN        NaN
2  torus_15_0.5     density      NaN       NaN        NaN

      data_name      method  corr  mse  dist2geod
0  torus_15_0.7        ours   NaN  NaN        NaN
1  torus_15_0.7  no density   NaN  NaN        NaN
2  torus_15_0.7     density   NaN  NaN        NaN

        data_name      method      corr        mse  dist2geod
0  torus_none_0.1        ours  0.951856   0.730998   0.115022
1  torus_none_0.1  no density  0.818501  16.464834   0.690944
2  torus_none_0.1     density  0.943621   2.002946   0.071560

     data_name      method      corr         mse  dist2geod
0  torus_5_0.1        ours  0.933522    1.143752   0.052090
1  torus_5_0.1  no density  0.636462  106.732790   1.244507
2  torus_5_0.1     density  0.939949    0.929766   0.021866

      data_name      method      corr         mse  dist2geod
0  torus_10_0.1        ours  0.902715    1.099917   0.038555
1  torus_10_0.1  no density  0.293168  564.651000   2.285672
2  torus_10_0.1     density  0.849951    1.189404   0.027707

      data_name      method      corr        mse  dist2geod
0  torus_50_0.1        ours  0.943642  33.529457   0.103066
1  torus_50_0.1  no density       NaN        NaN        NaN
2  torus_50_0.1     density       NaN        NaN        NaN

In [7]:
results = results.drop_duplicates()

In [8]:
results

            data_name      method      corr         mse  dist2geod
0   hemisphere_none_0        ours  0.983717    0.030749   0.006986
1   hemisphere_none_0  no density  0.910126    0.328954   0.074433
2   hemisphere_none_0     density  0.914932    0.287929   0.028052
0    ellipsoid_none_0        ours  0.960778    0.492454   0.035831
1    ellipsoid_none_0  no density  0.847388    2.403414   0.106092
..                ...         ...       ...         ...        ...
1        torus_10_0.1  no density  0.293168  564.651000   2.285672
2        torus_10_0.1     density  0.849951    1.189404   0.027707
0        torus_50_0.1        ours  0.943642   33.529457   0.103066
1        torus_50_0.1  no density       NaN         NaN        NaN
2        torus_50_0.1     density       NaN         NaN        NaN

[120 rows x 5 columns]

In [9]:
results[results['mse'].isna()]['data_name'].values

array(['hemisphere_15_0.3', 'hemisphere_15_0.3', 'hemisphere_15_0.3',
       'saddle_15_0.1', 'saddle_50_0.1', 'saddle_50_0.1', 'torus_15_0.5',
       'torus_15_0.5', 'torus_15_0.7', 'torus_15_0.7', 'torus_15_0.7',
       'torus_50_0.1', 'torus_50_0.1'], dtype=object)

In [10]:
len(results[results['mse'].isna()]['data_name'].values)

13

In [11]:
# dijk_res_list = []
# dijk_missing_list = []
# for name in data_names:
#     try:
#         # load from pickle
#         with open(f'../dijkstra/noisy_results/{name}.pkl', 'rb') as f:
#             res_dict = pickle.load(f)
#         dijk_res_list.append(res_df)
#     except:
#         dijk_missing_list.append(name)
#         continue
# dijk_results = pd.concat(dijk_res_list)

In [12]:
# name = data_names[-1]
# with open(f'../dijkstra/noisy_results/{name}.pkl', 'rb') as f:
#     res_dict = pickle.load(f)

In [13]:
# res_dict

In [14]:
results[results['data_name'].apply(lambda x: x.endswith('none_0'))]#[['data_name', 'method', 'mse']]

           data_name      method      corr       mse  dist2geod
0  hemisphere_none_0        ours  0.983717  0.030749   0.006986
1  hemisphere_none_0  no density  0.910126  0.328954   0.074433
2  hemisphere_none_0     density  0.914932  0.287929   0.028052
0   ellipsoid_none_0        ours  0.960778  0.492454   0.035831
1   ellipsoid_none_0  no density  0.847388  2.403414   0.106092
2   ellipsoid_none_0     density  0.922390  2.243079   0.032896
0       torus_none_0        ours  0.982601  0.353004   0.065092
1       torus_none_0  no density  0.907541  1.829810   0.085663
2       torus_none_0     density  0.968065  1.796790   0.015130
0      saddle_none_0        ours  0.955881  0.054671   0.013050
1      saddle_none_0  no density  0.949982  0.065696   0.033616
2      saddle_none_0     density  0.964598  0.095990   0.006502

In [15]:
results.to_csv('toy_results.csv')